# Generated by Django 2.2.16 on 2020-10-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('journal', 'journal'), ('run', 'run'), ('Finland', 'Finland')], max_length=50, null=True),
        ),
    ]
