# Generated by Django 2.2.16 on 2020-10-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Tag',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='journal',
            field=models.CharField(choices=[('NEJM', 'NEJM'), ('JACC', 'JACC'), ('Circulation', 'Circulation')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='published_year',
            field=models.CharField(choices=[('2016', '2016年'), ('2017', '2017年'), ('2018', '2018年'), ('2019', '2019年'), ('2020', '2020年')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('TAVR', 'TAVR'), ('CAD', 'CAD'), ('Economic', 'Economic')], max_length=50, null=True),
        ),
    ]
