# Generated by Django 2.2.16 on 2020-10-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201011_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
